monome/dust

docs/jah/ack/index.md, docs/jah/hello_ack/index.md, docs/jah/step/index.md
fixed broken links. also a bit more cleanup
=> fix ack docs

scripts/study/16sliders.lua
i find myself using this script for sanity checking and mix out is handy.
if it's destined to be part of a study w/ stuff getting added progressively, feel free to ignore (or for any other reason! 😉 )
/cc @tehn
=> control mix output w/ enc 1

scripts/artfwo/glut.lua
follow-up from #111 .
/cc @artfwo
=> remove unneeded cleanup

scripts/tehn/earthsea.lua, scripts/tehn/mlr.lua
=> remove unneeded engine stop from cleanup

lib/sc/Engine_KarplusRings.sc
change output routing for vol control, aux and insert fx
=> Minor output routing fix for KarplusRings.sc

docs/mark_eats/musicutil/index.html, docs/mark_eats/musicutil/ldoc.css, lib/lua/mark_eats/musicutil.lua, scripts/mark_eats/scales_demo.lua
Put musicutil.lua and associated demo script together into dust. Only small tweaks since yesterday.
Also generated a quick ldoc page for musicutil - not sure if this is a good idea or confusing given that the other docs in that folder are MD and for scripts and engines. Included for discussion 🙂
=> musicutil.lua and scales demo script

scripts/tehn/awake.lua
following the same approach as https://github.com/monome/dust/pull/131
=> add midi clock out to awake

scripts/tehn/playfair.lua
effects (delay, reverb) params removed in commit 5b69209e4d192d2bdc20c502c91df9cadc454d4e restored
=> fix playfair effects params again

scripts/justmat/foulplay.lua
8 tracks of euclidean rhythms with per-track trigger conditions and in app controls that add a performative sense while also alleviating the need for going back to the parameter menu so often. 
I plan on adding more trig conditions in the future.
This is based on playfair.
=> adding foulplay script

scripts/mhetrick/easygrain.lua, scripts/mhetrick/wormhole.lua, scripts/study/study1.lua, scripts/study/study2.lua, scripts/study/study3.lua
This is a deluxe version of spacetime from Norns Study 3.
=> Add wormhole

scripts/olivier/oblique_strategies.lua
On key press, this super simple script prints a random Oblique Strategy to the screen and generates a note (using the PolyPerc engine). A way to start the day.
=> Add Oblique Strategies script

scripts/jah/hello_ack.lua, scripts/jah/hello_gong.lua, scripts/tehn/earthsea.lua, scripts/tehn/mlr.lua
remove midi device event cleanup now handled in core norns logic, see monome/norns#470
=> remove unneeded midi device event cleanup

docs/justmat/foulplay/foulplay.md, scripts/justmat/foulplay.lua
Added a proper markdown doc for foulplay, located in dust/docs/justmat. I also added and/or trig logic to foulplay.
=> Proper docs and new trig conditions for Foulplay

docs/justmat/foulplay/foulplay.md, scripts/justmat/foulplay.lua
Finished adding the logical trigger conditions to Foulplay, and updated the docs accordingly.
=> Added Nand, Nor, and Xor trig conditions to Foulplay. updated docs.

scripts/tehn/playfair.lua
quick edit to save patterns using grid interface
- top row is parameter set selector (1-16)
- bottom rows are radio-button style pattern selector. hold to save, touch to load
changed ENC1 to be track select
changed KEY3 to start/stop
=> playfair patterns and grid support

lib/lua/mark_eats/graph.lua
These checks could be restrictive.
=> Minor fix to graph.lua - removed some unrequired checks for graph functions

lib/lua/mark_eats/passersby.lua, lib/sc/Engine_Passersby.sc, scripts/mark_eats/passersby.lua
New synth engine and midi-driven script
=> Passersby synth engine and script

scripts/nf/rebound.lua
As seen here: https://llllllll.co/t/approaching-norns/13236/2004
=> rebound: a kinetic sequencer

scripts/speakerdamage/channel_changer.lua
=> Add channel changer script

scripts/justmat/foulplay.lua
adds per track mute state to the pattern data. Also cleans up some comments.
=> foulplay - adds mute state to saves

lib/sc/Engine_SoftCut.sc, lib/sc/abstractions/SoftCutVoice.sc
requires https://github.com/monome/norns/pull/494
increase voice count
this is WIP, will add demo script
=> Softcut improvements

scripts/tehn/halfsecond.lua
very simple script to init softcut for live interaction/testing via maiden
=> softcut test

scripts/tehn/halfsecond.lua
=> softcut test addition

scripts/justmat/foulplay.lua
Minor change to avoid loading an old/ incompatible .data file.
=> foulplay: minor tweak to savestate/loadstate

scripts/declutter/boingg.lua
My first script - the traditional monome app 'boingg'. This script heavily based on @artfwo 's flin from which I learned a lot.
=> New script - Boingg

scripts/nf/rebound.lua
Use @markwheeler's MidiUtil library and add MIDI note out.
=> Rebound enhancements

scripts/nf/rebound.lua
Technical and cosmetic changes to make it easier to reason about melody and harmony.
=> More rebound enhancements

docs/jah/ack/index.md, lib/lua/jah/ack.lua, lib/sc/Engine_Ack.sc
- added a mutegroup, fixes #173 
- added dist command, fixes #94 
- added kill and multiKill command to kill/mute channels explicitly
- effects now operate in a ParGroup.
- improvement: refactored gate logic
=> additions to ack

lib/lua/mark_eats/formatters.lua, lib/lua/mark_eats/passersby.lua, scripts/mark_eats/passersby.lua
Minor updates mainly to keep up with midi api
=> Passersby v1.0.1 - new midi methods, formatters lib

scripts/justmat/foulplay.lua
Adds midi output with selectable note/channel per track. Also cleans up some comments and whitespace.
=> foulpay: adds midi output

docs/justmat/foulplay/foulplay.md
=> foulplay: updates docs

lib/lua/beatclock.lua, scripts/artfwo/flin.lua, scripts/artfwo/glut.lua, scripts/burn/kayan.lua, scripts/declutter/boingg.lua, scripts/gittifer/ekombi.lua, scripts/justmat/foulplay.lua, scripts/mhetrick/easygrain.lua, scripts/mhetrick/wormhole.lua, scripts/nf/rebound.lua, scripts/speakerdamage/channel_changer.lua, scripts/study/param.lua, scripts/study/study3.lua, scripts/tehn/awake.lua, scripts/tehn/earthsea.lua, scripts/tehn/mlr.lua, scripts/tehn/playfair.lua
this accompanies https://github.com/monome/norns/pull/571 and should be merged together. scripts by @antonhornquist and @markwheeler aren't currently updated to use param ids.
=> use params ids in scripts

lib/lua/mark_eats/passersby.lua
Switch to using new trigger param type from [norns#567](https://github.com/monome/norns/pull/567)
=> Passersby: Use trigger param for randomize

scripts/tehn/awake.lua
also stopped trashing the controlspec global
=> awake, use new params:add syntax

lib/lua/mark_eats/mollythepoly.lua, lib/sc/Engine_MollyThePoly.sc, scripts/mark_eats/molly_the_poly.lua
New synth engine and script for generating patches.
Classic polysynth: Voice structure like a Juno with some extra modulation like a Jupiter and ring mod because CS-80. But, you know, different.
Requires norns [PR 567](https://github.com/monome/norns/pull/567)
=> Molly the Poly engine and script

scripts/nf/rebound.lua
fix midi syntax (there is no more `send_all`)
also whitespace
=> fix rebound midi

scripts/dndrks/cranes.lua
@dndrks 
this is amazing!!
how do i record onto buffer 2?
=> crane: new syntax params

scripts/dndrks/cranes.lua
made clearer that cranes is two unique voices of one buffer.
=> update language for clearer syntax

scripts/M4R71N/ANDR.lua
ANDR is a Markov chain inspired sequencer. BTW I've made a README.md but i am not sure where to put it.
=> Create Folder + ANDR script

scripts/M4R71N/ANDR.lua
- update param syntax
- cleanup whitespace
- format top instructions to fit on norns screen
=> andr fixes

scripts/justmat/paths.lua
Paths is a step sequencer script I have been working on. 
btw This is still using the old params syntax. I will change it to the new syntax after I can install the Norns update tomorrow.
=> adds new script "paths"

scripts/justmat/paths.lua
@notjustmat 
ready for inclusion in update
=> paths, update syntax

scripts/nf/rebound.lua
Hi @nf it looks like the scale gen param was off by one (C is 0 in MIDI), I think this fixes.
Been having fun with the script!
=> Rebound scale gen off by one fix

scripts/study/draw.lua, scripts/tehn/awake.lua, scripts/tehn/mlr.lua
new feature add.
also fix awake.
also proof-of-concepts (screen state saving, no engine definition) in draw.lua
=> mlr: add recalls

scripts/justmat/paths.lua
Small update to allow use without a grid. Also adds an option to enable keybed highlighting of black notes.
=> paths: allows entering step edit mode without a grid

scripts/justmat/paths.lua
=> paths: cleans up some nits

lib/lua/mark_eats/formatters.lua, lib/lua/mark_eats/mollythepoly.lua, lib/lua/mark_eats/passersby.lua
Small refactor of my formatter lib to make it more flexible
=> formatter lib refactor

scripts/mark_eats/tuner.lua
Very simple script that displays the existing SC pitch polls.
=> New script - tuner

scripts/mark_eats/molly_the_poly.lua
not at all sure if this is the right way to go about this (or if it's even generally desired) but useful for me...
no hard feelings either way!
/cc @markwheeler
=> add pitch bend range param

scripts/justmat/paths.lua
Paths is now capable of 4 tracks, each with up to 16 patterns of independent length and  per-step probability settings.
=> paths: clean up, and various additions

scripts/mark_eats/tuner.lua
Small addition to tuner script that lets you hear a reference note.
=> Tuner v1.0.1

lib/sc/Engine_SoftCut.sc, lib/sc/abstractions/BufUtil.sc, scripts/tehn/mlr.lua
i guess `buf.write` wanted `asInt`
=> mlr clip save

lib/sc/Engine_MollyThePoly.sc, scripts/mark_eats/loom.lua
Major perf improvements and minor bugs squashed.
=> Loom performance improvements

scripts/justmat/paths.lua
After my last update, pattern loading/ switching wasn't working at all as intended. This restores correct functionality.
=> paths: pattern load bug fix

lib/sc/Engine_SoftCut.sc, lib/sc/abstractions/PatchMatrix.sc
looked over softcut bus management again. it seems to work fine, but cleaned up anyway. now softcut makes its own in/out busses for clarity.
=> Softcut fix busses again

scripts/mark_eats/loom.lua
- Fixes when using external clock
- Minor grid redraw fixes
- Limit BPM
- Code formatting
=> Loom v1.0.2

scripts/dndrks/cranes.lua
speed options for buffer 2 now include: {-2.0, -1.0, -0.5, -0.25, 0.25, 0.5, 1.0, 2.0, 4.0}
buffer 1 still: {0.25, 0.5, 1.0, 2.0}
=> cranes: update with reverse playback + 4x speed

lib/lua/ansible/kria.lua, lib/lua/ansible/scales.lua, scripts/junklight/Kria_MIDI.lua
Release 0 of Kria 
essentially a fairly vanilla port of Ansible Kria 
Presets/persistence needs rewriting (although it works)
=> kria release 0

scripts/mark_eats/loom.lua
Tiny fixes for Loom UI that make sense once PR #253 is merged
=> Loom v1.0.3

scripts/justmat/strides.lua
Strides is a 4 track finger drum pattern recorder for grid.
=> new script, Strides.

docs/sbaio/zellen/index.md, scripts/sbaio/zellen.lua
as previewed in the "approaching: norns" thread on lines, here's zellen, a game of life based sequencer for norns.
=> zellen - game of life based sequencer

scripts/tyler/roda.lua
-ppq parameter
-load/save parameter
-alt key
=> roda: improved controls

lib/lua/ansible/meadowphysics.lua, scripts/alphacactus/mp_ack.lua
had an old version of the meadowphysics.lua library on my last pull request. updated with the correct version.
=> fixed meadowphysics

docs/sbaio/zellen/index.md, scripts/sbaio/zellen.lua
* set root note to C3 in order to match initial parameter setting
* correction for documentation
=> minor fix for zellen

scripts/justmat/strides.lua
extends strides to 8 finger drum style pattern recorders, and 8 encoder recorders that send midi cc's.
Also fixes a few small bugs.
=> strides enhancements and improvements 

scripts/justmat/strides.lua
Adds midi note output to the drum pads.
=> strides: extends midi implementation

scripts/justmat/strides.lua
The joys of git are truly unending.
I guess my last commit over-wrote a previous fix.
=> strides: re-apply bug fix that got overwritten

scripts/dndrks/less_concepts.lua
- utilizes @markwheeler 's `Passersby` engine
- grid-enabled, but not grid-dependent
- midi-enabled, two channels of notes
- [here](https://llllllll.co/uploads/default/original/3X/d/1/d19e15fb63831f7883d2660f77c83cc56811a6bc.png) for grid legend
=> add less concepts, 1-d CA sequencer

scripts/justmat/strides.lua
Fixes a bug in the pattern linearize function.
cleans up.
adds send options "audio" "audio + midi" and/or "midi".
=> strides: bug fixes, cleanup, and enhancements 

lib/lua/ansible/gridscales.lua, lib/lua/ansible/meadowphysics.lua, scripts/alphacactus/mp_ack.lua, scripts/alphacactus/mp_midi.lua
implemented a `meadowphsyics` script with midi capabilities. minor update to the `meadowphysics` library. also added a `gridscales` library that functions similar to how ansible scales work.
=> meadowphysics update / grid scales library

lib/lua/jah/formatters.lua, lib/lua/mark_eats/ui.lua, scripts/mark_eats/ui_demo.lua
Small fixes and additions to ui.lua, formatters.lua and ui demo script.
Just getting some lib updates in before 2.0!
=> Updates to ui and formatters libs
